drop table if exists users cascade;
drop table if exists posts cascade;
drop table if exists messages cascade;
drop table if exists roles cascade;
drop table if exists users_friends cascade;
drop table if exists users_roles cascade;

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS posts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR(2000)                           NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    url       VARCHAR(4000)                           NOT NULL,
    author_id BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id),
    CONSTRAINT fk_posts_to_users FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS messages
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id BIGINT                                  NOT NULL,
    to_id   BIGINT                                  NOT NULL,
    text    VARCHAR(4000)                           NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id),
    CONSTRAINT fk_messages_to_users1 FOREIGN KEY (from_id) REFERENCES users (id),
    CONSTRAINT fk_messages_to_users2 FOREIGN KEY (to_id) REFERENCES users (id)

);

CREATE TABLE IF NOT EXISTS users_friends
(
    user_id   BIGINT,
    friend_id BIGINT,
    CONSTRAINT pk_uf PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_uf_to_users1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_uf_to_users2 FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users_roles
(
    user_id BIGINT,
    role_id BIGINT,
    CONSTRAINT pk_ur PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_ur_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_to_roles FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

insert into roles (name)
values ('ROLE_USER'),
       ('ROLE_ADMIN');
